# Generated by Django 3.2.8 on 2022-02-01 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_posts', '0028_notification'),
        ('users', '0010_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookmarked_posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_posts.newsposts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='saved_post',
            field=models.ManyToManyField(related_name='saved_post', through='users.bookmarked_posts', to='news_posts.NewsPosts'),
        ),
    ]
