# Generated by Django 3.2.8 on 2022-01-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_posts', '0028_notification'),
        ('users', '0010_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_post',
            field=models.ManyToManyField(related_name='saved_post', to='news_posts.NewsPosts'),
        ),
    ]
