# Generated by Django 3.2.8 on 2022-02-09 00:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220201_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarked_posts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
