# Generated by Django 3.2.8 on 2022-02-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_directmessage_content'),
        ('users', '0012_bookmarked_posts_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='room',
            field=models.ManyToManyField(related_name='created_rooms', to='chat.DMRoom'),
        ),
    ]
