# Generated by Django 3.2.8 on 2021-11-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_remove_communities_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='communities',
            name='updated_at',
            field=models.DateTimeField(auto_now=True,),
        ),
    ]
