# Generated by Django 3.2.8 on 2021-11-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_auto_20211126_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communities',
            name='name',
            field=models.CharField(max_length=21, unique=True),
        ),
    ]
