# Generated by Django 3.2.8 on 2021-12-01 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_communities_community_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communities',
            old_name='COMMUNITY_TYPE',
            new_name='community_type',
        ),
    ]
