# Generated by Django 3.2.8 on 2021-12-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_rename_community_type_communities_community_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='communities',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='写真'),
        ),
    ]
