# Generated by Django 3.2.8 on 2021-12-15 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_about'),
        ('communities', '0009_alter_communities_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communities',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='users.user'),
        ),
    ]
