# Generated by Django 3.2.8 on 2021-12-15 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_about'),
        ('communities', '0010_alter_communities_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communities',
            name='admin',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
