# Generated by Django 3.2.8 on 2021-10-13 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('news_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsposts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
