# Generated by Django 3.2.8 on 2021-11-24 01:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_remove_communities_updated_at'),
        ('news_posts', '0004_remove_newsposts_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsposts',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='communities.communities'),
            preserve_default=False,
        ),
    ]
