# Generated by Django 3.2.8 on 2021-11-24 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_posts', '0005_newsposts_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsposts',
            name='community',
        ),
    ]
