# Generated by Django 3.2.8 on 2021-11-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_posts', '0010_alter_newsposts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsposts',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
