# Generated by Django 3.2.8 on 2021-12-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_posts', '0011_alter_newsposts_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsposts',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='写真'),
        ),
    ]
