# Generated by Django 3.2.8 on 2021-12-08 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_about'),
        ('news_posts', '0012_newsposts_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsposts',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
