# Generated by Django 3.2.8 on 2021-12-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_posts', '0013_alter_newsposts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsposts',
            name='content',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
