# Generated by Django 3.2.8 on 2021-12-13 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_posts', '0017_newsposts_contributer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsposts',
            name='contributer',
        ),
    ]
