# Generated by Django 3.2.8 on 2021-12-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_posts', '0019_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
