# Generated by Django 3.2.8 on 2022-01-17 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_managers'),
        ('news_posts', '0020_alter_comment_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voted_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_post', to='news_posts.newsposts')),
                ('voted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
