# Generated by Django 3.2.8 on 2022-01-17 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_managers'),
        ('news_posts', '0021_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voted_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voted_post', to='news_posts.newsposts'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
