# Generated by Django 3.2.8 on 2022-01-18 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_managers'),
        ('news_posts', '0022_auto_20220117_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voted_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='voted_post', to='news_posts.newsposts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='voted_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
