# Generated by Django 3.2.8 on 2022-01-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_posts', '0023_auto_20220118_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='flag',
        ),
    ]
