# Generated by Django 3.2.8 on 2022-01-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_posts', '0024_remove_vote_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='flag',
            field=models.IntegerField(default=0),
        ),
    ]
