# Generated by Django 3.2.8 on 2022-01-24 04:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0011_alter_communities_admin'),
        ('news_posts', '0025_vote_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsposts',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='community', to='communities.communities'),
            preserve_default=False,
        ),
    ]
