# Generated by Django 3.2.8 on 2022-02-05 05:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news_posts', '0032_auto_20220204_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replay',
            name='mension',
        ),
        migrations.AddField(
            model_name='replay',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='replay_target', to='news_posts.comment'),
            preserve_default=False,
        ),
    ]
