# Generated by Django 3.2.8 on 2022-02-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_posts', '0035_alter_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(blank=True, max_length=624, null=True),
        ),
    ]
