# Generated by Django 3.2.8 on 2022-06-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_posts', '0040_alter_comment_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsposts',
            name='latest_commented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
