# Generated by Django 3.2.8 on 2022-06-10 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0011_alter_communities_admin'),
        ('news_posts', '0042_comment_latest_replayed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsposts',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communities_post', to='communities.communities'),
        ),
    ]
