# Generated by Django 3.2.8 on 2022-06-15 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_email'),
        ('news_posts', '0043_alter_newsposts_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voted_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_user', to='users.user'),
        ),
    ]
