# Generated by Django 3.2.8 on 2022-06-17 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_email'),
        ('news_posts', '0045_remove_newsposts_saved_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='newsposts',
            old_name='vote',
            new_name='like',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='like',
            name='liked_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='news_posts.newsposts'),
        ),
        migrations.AddField(
            model_name='like',
            name='liked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_user', to='users.user'),
        ),
    ]
