# Generated by Django 3.2.8 on 2022-02-15 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_bookmarked_posts_created_at'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmroom',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dm_author', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
