# Generated by Django 3.2.8 on 2022-02-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_dmroom_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='content',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
