# Generated by Django 3.2.8 on 2022-02-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_user_room'),
        ('chat', '0003_alter_directmessage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmroom',
            name='users',
            field=models.ManyToManyField(related_name='created_dm_room_users', to='users.User'),
        ),
    ]
