# Generated by Django 3.2.8 on 2022-02-18 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_user_room'),
        ('chat', '0005_remove_dmroom_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.BooleanField(default=False)),
                ('rejection', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_dm_invite', to='users.user')),
                ('received_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_dm_receive', to='users.user')),
            ],
        ),
    ]
