# Generated by Django 3.2.8 on 2022-02-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_dminvite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dminvite',
            old_name='approval',
            new_name='accept',
        ),
        migrations.RenameField(
            model_name='dminvite',
            old_name='rejection',
            new_name='ignore',
        ),
    ]
