# Generated by Django 3.2.8 on 2022-09-16 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_dminvite_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='recipient_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_message', to='chat.directmessage'),
        ),
    ]
