# Generated by Django 3.2.8 on 2022-09-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_directmessage_recipient_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmroom',
            name='latest_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
